package desensamblador;

import java.util.HashMap;

public class Z80Mnemonicos {
    public static final HashMap<Integer, String> mnemonicos = new HashMap<>();
    public static final HashMap<Integer, Integer> parametros = new HashMap<>();

        static {
//MAIN INSTRUCTIONS
            mnemonicos.put(0x00, "NOP");
            mnemonicos.put(0x01, "LD BC, %04X");
    parametros.put(0x01, 2);
            mnemonicos.put(0x02, "LD (BC),A");
            mnemonicos.put(0x03, "INC BC");
            mnemonicos.put(0x04, "INC B");
            mnemonicos.put(0x05, "DEC B");
            mnemonicos.put(0x06, "LD B, %02X");
    parametros.put(0x06, 1);
            mnemonicos.put(0x07, "RLCA");
            mnemonicos.put(0x08, "EX AF,AF'");
            mnemonicos.put(0x09, "ADD HL,BC");
            mnemonicos.put(0x0A, "LD A,(BC)");
            mnemonicos.put(0x0B, "DEC BC");
            mnemonicos.put(0x0C, "INC C");
            mnemonicos.put(0x0D, "DEC C");
            mnemonicos.put(0x0E, "LD C, %02X");
    parametros.put(0x0E, 1);
            mnemonicos.put(0x0F, "RRCA");
            mnemonicos.put(0x10, "DJNZ %02X");
            parametros.put(0x10, 1);
            mnemonicos.put(0x11, "LD DE, %04X");
    parametros.put(0x11, 2);
            mnemonicos.put(0x12, "LD (DE),A");
            mnemonicos.put(0x13, "INC DE");
            mnemonicos.put(0x14, "INC D");
            mnemonicos.put(0x15, "DEC D");
            mnemonicos.put(0x16, "LD D, %02X");
    parametros.put(0x16, 1);
            mnemonicos.put(0x17, "RLA");
            mnemonicos.put(0x18, "JR %02X");
    parametros.put(0x18, 1);
            mnemonicos.put(0x19, "ADD HL,DE");
            mnemonicos.put(0x1A, "LD A,(DE)");
            mnemonicos.put(0x1B, "DEC DE");
            mnemonicos.put(0x1C, "INC E");
            mnemonicos.put(0x1D, "DEC E");
            mnemonicos.put(0x1E, "LD E, %02X");
    parametros.put(0x1E, 1);
            mnemonicos.put(0x1F, "RRA");
            mnemonicos.put(0x20, "JR NZ, %02X");
    parametros.put(0x20, 1);
            mnemonicos.put(0x21, "LD HL, %04X");
    parametros.put(0x21, 2);
            mnemonicos.put(0x22, "LD (%04X), HL");
    parametros.put(0x22, 2);
            mnemonicos.put(0x23, "INC HL");
            mnemonicos.put(0x24, "INC H");
            mnemonicos.put(0x25, "DEC H");
            mnemonicos.put(0x26, "LD H, %02X");
    parametros.put(0x26, 1);
            mnemonicos.put(0x27, "DAA");
            mnemonicos.put(0x28, "JR Z, %02X");
    parametros.put(0x28, 1);
            mnemonicos.put(0x29, "ADD HL, HL");
            mnemonicos.put(0x2A, "LD HL, (%04X)");
    parametros.put(0X2A, 2);
            mnemonicos.put(0x2B, "DEC HL");
            mnemonicos.put(0x2C, "INC L");
            mnemonicos.put(0x2D, "DEC L");
            mnemonicos.put(0x2E, "LD L, %02X");
    parametros.put(0x2E, 1);
            mnemonicos.put(0x2F, "CPL");
            mnemonicos.put(0x30, "JR NC, %02X");
    parametros.put(0x30, 1);
            mnemonicos.put(0x31, "LD SP, %04X");
    parametros.put(0x31, 2);
            mnemonicos.put(0x32, "LD (%04X), A");
    parametros.put(0x32, 2);
            mnemonicos.put(0x33, "INC SP");
            mnemonicos.put(0x34, "INC (HL)");
            mnemonicos.put(0x35, "DEC (HL)");
            mnemonicos.put(0x36, "LD (HL), %02X");
    parametros.put(0x36, 1);
            mnemonicos.put(0x37, "SCF");
            mnemonicos.put(0x38, "JR C, %02X");
    parametros.put(0x38, 1);
            mnemonicos.put(0x39, "ADD HL, SP");
            mnemonicos.put(0x3A, "LD A,(%04X)");
    parametros.put(0x3A, 2);
            mnemonicos.put(0x3B, "DEC SP");
            mnemonicos.put(0x3C, "INC A");
            mnemonicos.put(0x3D, "DEC A");
            mnemonicos.put(0x3E, "LD A, %02X");    
    parametros.put(0x3E, 1);
            mnemonicos.put(0x3F, "CCF");
        //LD B
            mnemonicos.put(0x40, "LD B, B");
            mnemonicos.put(0x41, "LD B, C");
            mnemonicos.put(0x42, "LD B, D");
            mnemonicos.put(0x43, "LD B, E");
            mnemonicos.put(0x44, "LD B, H");
            mnemonicos.put(0x45, "LD B, L");
            mnemonicos.put(0x46, "LD B, (HL)");
            mnemonicos.put(0x47, "LD B, A");
        //LD C
            mnemonicos.put(0x48, "LD C, B");
            mnemonicos.put(0x49, "LD C, C");
            mnemonicos.put(0x4A, "LD C, D");
            mnemonicos.put(0x4B, "LD C, E");
            mnemonicos.put(0x4C, "LD C, H");
            mnemonicos.put(0x4D, "LD C, L");
            mnemonicos.put(0x4E, "LD C, (HL)");
            mnemonicos.put(0x4F, "LD C, A");
        //LD D
            mnemonicos.put(0x50, "LD D, B");
            mnemonicos.put(0x51, "LD D, C");
            mnemonicos.put(0x52, "LD D, D");
            mnemonicos.put(0x53, "LD D, E");
            mnemonicos.put(0x54, "LD D, H");
            mnemonicos.put(0x55, "LD D, L");
            mnemonicos.put(0x56, "LD D, (HL)");
            mnemonicos.put(0x57, "LD D, A");
        //LD E 
            mnemonicos.put(0x58, "LD E, B");
            mnemonicos.put(0x59, "LD E, C");
            mnemonicos.put(0x5A, "LD E, D");
            mnemonicos.put(0x5B, "LD E, E");
            mnemonicos.put(0x5C, "LD E, H");
            mnemonicos.put(0x5D, "LD E, L");
            mnemonicos.put(0x5E, "LD E, (HL)");
            mnemonicos.put(0x5F, "LD E, A");
        //LD H
            mnemonicos.put(0x60, "LD H, B");
            mnemonicos.put(0x61, "LD H, C");
            mnemonicos.put(0x62, "LD H, D");
            mnemonicos.put(0x63, "LD H, E");
            mnemonicos.put(0x64, "LD H, H");
            mnemonicos.put(0x65, "LD H, L");
            mnemonicos.put(0x66, "LD H, (HL)");
            mnemonicos.put(0x67, "LD H, A");
        //LD L
            mnemonicos.put(0x68, "LD L, B");
            mnemonicos.put(0x69, "LD L, C");
            mnemonicos.put(0x6A, "LD L, D");
            mnemonicos.put(0x6B, "LD L, E");
            mnemonicos.put(0x6C, "LD L, H");
            mnemonicos.put(0x6D, "LD L, L");
            mnemonicos.put(0x6E, "LD L, (HL)");
            mnemonicos.put(0x6F, "LD L, A");
        //LD (HL)
            mnemonicos.put(0x70, "LD (HL), B");
            mnemonicos.put(0x71, "LD (HL), C");
            mnemonicos.put(0x72, "LD (HL), D");
            mnemonicos.put(0x73, "LD (HL), E");               
            mnemonicos.put(0x74, "LD (HL), H");
            mnemonicos.put(0x75, "LD (HL), L");
            
            mnemonicos.put(0x76, "HALT");
            
            mnemonicos.put(0x77, "LD (HL), A");
        //LD A    
            mnemonicos.put(0x78, "LD A, B");
            mnemonicos.put(0x79, "LD A, C");
            mnemonicos.put(0x7A, "LD A, D");
            mnemonicos.put(0x7B, "LD A, E");
            mnemonicos.put(0x7C, "LD A, H");
            mnemonicos.put(0x7D, "LD A, L");
            mnemonicos.put(0x7E, "LD A, (HL)");
            mnemonicos.put(0x7F, "LD A, A");
        //ADD A
            mnemonicos.put(0x80, "ADD A, B");
            mnemonicos.put(0x81, "ADD A, C");
            mnemonicos.put(0x82, "ADD A, D");
            mnemonicos.put(0x83, "ADD A, E");
            mnemonicos.put(0x84, "ADD A, H");
            mnemonicos.put(0x85, "ADD A, L");
            mnemonicos.put(0x86, "ADD A, (HL)");
            mnemonicos.put(0x87, "ADD A, A");
        //ADC A, r
            mnemonicos.put(0x88, "ADC A, B");
            mnemonicos.put(0x89, "ADC A, C");
            mnemonicos.put(0x8A, "ADC A, D");
            mnemonicos.put(0x8B, "ADC A, E");
            mnemonicos.put(0x8C, "ADC A, H");
            mnemonicos.put(0x8D, "ADC A, L");
            mnemonicos.put(0x8E, "ADC A, (HL)");
            mnemonicos.put(0x8F, "ADC A, A");
        //SUB r
            mnemonicos.put(0x90, "SUB B");
            mnemonicos.put(0x91, "SUB C");
            mnemonicos.put(0x92, "SUB D");
            mnemonicos.put(0x93, "SUB E");
            mnemonicos.put(0x94, "SUB H");
            mnemonicos.put(0x95, "SUB L");
            mnemonicos.put(0x96, "SUB (HL)");
            mnemonicos.put(0x97, "SUB A");
        //SBC A, r
            mnemonicos.put(0x98, "SBC A, B");
            mnemonicos.put(0x99, "SBC A, C");
            mnemonicos.put(0x9A, "SBC A, D");
            mnemonicos.put(0x9B, "SBC A, E");
            mnemonicos.put(0x9C, "SBC A, H");
            mnemonicos.put(0x9D, "SBC A, L");
            mnemonicos.put(0x9E, "SBC A, (HL)");
            mnemonicos.put(0x9F, "SBC A, A");
        //AND r
            mnemonicos.put(0xA0, "AND B");
            mnemonicos.put(0xA1, "AND C");
            mnemonicos.put(0xA2, "AND D");
            mnemonicos.put(0xA3, "AND E");
            mnemonicos.put(0xA4, "AND H");
            mnemonicos.put(0xA5, "AND L");
            mnemonicos.put(0xA6, "AND (HL)");
            mnemonicos.put(0xA7, "AND A");
        //XOR r
            mnemonicos.put(0xA8, "XOR B");
            mnemonicos.put(0xA9, "XOR C");
            mnemonicos.put(0xAA, "XOR D");
            mnemonicos.put(0xAB, "XOR E");
            mnemonicos.put(0xAC, "XOR H");
            mnemonicos.put(0xAD, "XOR L");
            mnemonicos.put(0xAE, "XOR (HL)");
            mnemonicos.put(0xAF, "XOR A");
        //OR r
            mnemonicos.put(0xB0, "OR B");
            mnemonicos.put(0xB1, "OR C");
            mnemonicos.put(0xB2, "OR D");
            mnemonicos.put(0xB3, "OR E");
            mnemonicos.put(0xB4, "OR H");
            mnemonicos.put(0xB5, "OR L");
            mnemonicos.put(0xB6, "OR (HL)");
            mnemonicos.put(0xB7, "OR A");
        //CP r
            mnemonicos.put(0xB8, "CP B");
            mnemonicos.put(0xB9, "CP C");
            mnemonicos.put(0xBA, "CP D");
            mnemonicos.put(0xBB, "CP E");
            mnemonicos.put(0xBC, "CP H");
            mnemonicos.put(0xBD, "CP L");
            mnemonicos.put(0xBE, "CP (HL)");
            mnemonicos.put(0xBF, "CP A");

            mnemonicos.put(0xC0, "RET NZ");
            mnemonicos.put(0xC1, "POP BC");
            mnemonicos.put(0xC2, "JP NZ, %04X");
        parametros.put(0xC2, 2);
            mnemonicos.put(0xC3, "JP %04X");
        parametros.put(0xC3, 2);
            mnemonicos.put(0xC4, "CALL NZ, %04X");
        parametros.put(0xC4, 2);
            mnemonicos.put(0xC5, "PUSH BC");
            mnemonicos.put(0xC6, "ADD A, %02X");
        parametros.put(0xC6, 1);
            mnemonicos.put(0xC7, "RST 00h");
            mnemonicos.put(0xC8, "RET Z");
            mnemonicos.put(0xC9, "RET");
            mnemonicos.put(0xCA, "JP Z, %04X");
        parametros.put(0xCA, 2);
        
        //BIT
            mnemonicos.put(0xCB00, "RLC B");
            mnemonicos.put(0xCB01, "RLC C");
            mnemonicos.put(0xCB02, "RLC D");
            mnemonicos.put(0xCB03, "RLC E");
            mnemonicos.put(0xCB04, "RLC H");
            mnemonicos.put(0xCB05, "RLC L");
            mnemonicos.put(0xCB06, "RLC (HL)");
            mnemonicos.put(0xCB07, "RLC A");
            mnemonicos.put(0xCB08, "RRC B");
            mnemonicos.put(0xCB09, "RRC C");
            mnemonicos.put(0xCB0A, "RRC D");
            mnemonicos.put(0xCB0B, "RRC E");
            mnemonicos.put(0xCB0C, "RRC H");
            mnemonicos.put(0xCB0D, "RRC L");
            mnemonicos.put(0xCB0E, "RRC (HL)");
            mnemonicos.put(0xCB0F, "RRC A");
            mnemonicos.put(0xCB10, "RL B");
            mnemonicos.put(0xCB11, "RL C");
            mnemonicos.put(0xCB12, "RL D");
            mnemonicos.put(0xCB13, "RL E");
            mnemonicos.put(0xCB14, "RL H");
            mnemonicos.put(0xCB15, "RL L");
            mnemonicos.put(0xCB16, "RL (HL)");
            mnemonicos.put(0xCB17, "RL A");
            mnemonicos.put(0xCB18, "RR B");
            mnemonicos.put(0xCB19, "RR C");
            mnemonicos.put(0xCB1A, "RR D");
            mnemonicos.put(0xCB1B, "RR E");
            mnemonicos.put(0xCB1C, "RR H");
            mnemonicos.put(0xCB1D, "RR L");
            mnemonicos.put(0xCB1E, "RR (HL)");
            mnemonicos.put(0xCB1F, "RR A");
            mnemonicos.put(0xCB20, "SLA B");
            mnemonicos.put(0xCB21, "SLA C");
            mnemonicos.put(0xCB22, "SLA D");
            mnemonicos.put(0xCB23, "SLA E");
            mnemonicos.put(0xCB24, "SLA H");
            mnemonicos.put(0xCB25, "SLA L");
            mnemonicos.put(0xCB26, "SLA (HL)");
            mnemonicos.put(0xCB27, "SLA A");
            mnemonicos.put(0xCB28, "SRA B");
            mnemonicos.put(0xCB29, "SRA C");
            mnemonicos.put(0xCB2A, "SRA D");
            mnemonicos.put(0xCB2B, "SRA E");
            mnemonicos.put(0xCB2C, "SRA H");
            mnemonicos.put(0xCB2D, "SRA L");
            mnemonicos.put(0xCB2E, "SRA (HL)");
            mnemonicos.put(0xCB2F, "SRA A");
            mnemonicos.put(0xCB30, "SLL B");
            mnemonicos.put(0xCB31, "SLL C");
            mnemonicos.put(0xCB32, "SLL D");
            mnemonicos.put(0xCB33, "SLL E");
            mnemonicos.put(0xCB34, "SLL H");
            mnemonicos.put(0xCB35, "SLL L");
            mnemonicos.put(0xCB36, "SLL (HL)");
            mnemonicos.put(0xCB37, "SLL A");
            mnemonicos.put(0xCB38, "SRL B");
            mnemonicos.put(0xCB39, "SRL C");
            mnemonicos.put(0xCB3A, "SRL D");
            mnemonicos.put(0xCB3B, "SRL E");
            mnemonicos.put(0xCB3C, "SRL H");
            mnemonicos.put(0xCB3D, "SRL L");
            mnemonicos.put(0xCB3E, "SRL (HL)");
            mnemonicos.put(0xCB3F, "SRL A");
            mnemonicos.put(0xCB40, "BIT 0,B");
            mnemonicos.put(0xCB41, "BIT 0,C");
            mnemonicos.put(0xCB42, "BIT 0,D");
            mnemonicos.put(0xCB43, "BIT 0,E");
            mnemonicos.put(0xCB44, "BIT 0,H");
            mnemonicos.put(0xCB45, "BIT 0,L");
            mnemonicos.put(0xCB46, "BIT 0,(HL)");
            mnemonicos.put(0xCB47, "BIT 0,A");
            mnemonicos.put(0xCB48, "BIT 1,B");
            mnemonicos.put(0xCB49, "BIT 1,C");
            mnemonicos.put(0xCB4A, "BIT 1,D");
            mnemonicos.put(0xCB4B, "BIT 1,E");
            mnemonicos.put(0xCB4C, "BIT 1,H");
            mnemonicos.put(0xCB4D, "BIT 1,L");
            mnemonicos.put(0xCB4E, "BIT 1,(HL)");
            mnemonicos.put(0xCB4F, "BIT 1,A");
            mnemonicos.put(0xCB50, "BIT 2,B");
            mnemonicos.put(0xCB51, "BIT 2,C");
            mnemonicos.put(0xCB52, "BIT 2,D");
            mnemonicos.put(0xCB53, "BIT 2,E");
            mnemonicos.put(0xCB54, "BIT 2,H");
            mnemonicos.put(0xCB55, "BIT 2,L");
            mnemonicos.put(0xCB56, "BIT 2,(HL)");
            mnemonicos.put(0xCB57, "BIT 2,A");
            mnemonicos.put(0xCB58, "BIT 3,B");
            mnemonicos.put(0xCB59, "BIT 3,C");
            mnemonicos.put(0xCB5A, "BIT 3,D");
            mnemonicos.put(0xCB5B, "BIT 3,E");
            mnemonicos.put(0xCB5C, "BIT 3,H");
            mnemonicos.put(0xCB5D, "BIT 3,L");
            mnemonicos.put(0xCB5E, "BIT 3,(HL)");
            mnemonicos.put(0xCB5F, "BIT 3,A");            
            mnemonicos.put(0xCB60, "BIT 4,B");
            mnemonicos.put(0xCB61, "BIT 4,C");
            mnemonicos.put(0xCB62, "BIT 4,D");
            mnemonicos.put(0xCB63, "BIT 4,E");
            mnemonicos.put(0xCB64, "BIT 4,H");
            mnemonicos.put(0xCB65, "BIT 4,L");
            mnemonicos.put(0xCB66, "BIT 4,(HL)");
            mnemonicos.put(0xCB67, "BIT 4,A");
            mnemonicos.put(0xCB68, "BIT 5,B");
            mnemonicos.put(0xCB69, "BIT 5,C");
            mnemonicos.put(0xCB6A, "BIT 5,D");
            mnemonicos.put(0xCB6B, "BIT 5,E");
            mnemonicos.put(0xCB6C, "BIT 5,H");
            mnemonicos.put(0xCB6D, "BIT 5,L");
            mnemonicos.put(0xCB6E, "BIT 5,(HL)");
            mnemonicos.put(0xCB6F, "BIT 5,A");
            mnemonicos.put(0xCB70, "BIT 6,B");
            mnemonicos.put(0xCB71, "BIT 6,C");
            mnemonicos.put(0xCB72, "BIT 6,D");
            mnemonicos.put(0xCB73, "BIT 6,E");
            mnemonicos.put(0xCB74, "BIT 6,H");
            mnemonicos.put(0xCB75, "BIT 6,L");
            mnemonicos.put(0xCB76, "BIT 6,(HL)");
            mnemonicos.put(0xCB77, "BIT 6,A");
            mnemonicos.put(0xCB78, "BIT 7,B");
            mnemonicos.put(0xCB79, "BIT 7,C");
            mnemonicos.put(0xCB7A, "BIT 7,D");
            mnemonicos.put(0xCB7B, "BIT 7,E");
            mnemonicos.put(0xCB7C, "BIT 7,H");
            mnemonicos.put(0xCB7D, "BIT 7,L");
            mnemonicos.put(0xCB7E, "BIT 7,(HL)");
            mnemonicos.put(0xCB7F, "BIT 7,A");
            mnemonicos.put(0xCB80, "RES 0,B");
            mnemonicos.put(0xCB81, "RES 0,C");
            mnemonicos.put(0xCB82, "RES 0,D");
            mnemonicos.put(0xCB83, "RES 0,E");
            mnemonicos.put(0xCB84, "RES 0,H");
            mnemonicos.put(0xCB85, "RES 0,L");
            mnemonicos.put(0xCB86, "RES 0,(HL)");
            mnemonicos.put(0xCB87, "RES 0,A");
            mnemonicos.put(0xCB88, "RES 1,B");
            mnemonicos.put(0xCB89, "RES 1,C");
            mnemonicos.put(0xCB8A, "RES 1,D");
            mnemonicos.put(0xCB8B, "RES 1,E");
            mnemonicos.put(0xCB8C, "RES 1,H");
            mnemonicos.put(0xCB8D, "RES 1,L");
            mnemonicos.put(0xCB8E, "RES 1,(HL)");
            mnemonicos.put(0xCB8F, "RES 1,A");
            mnemonicos.put(0xCB90, "RES 2,B");
            mnemonicos.put(0xCB91, "RES 2,C");
            mnemonicos.put(0xCB92, "RES 2,D");
            mnemonicos.put(0xCB93, "RES 2,E");
            mnemonicos.put(0xCB94, "RES 2,H");
            mnemonicos.put(0xCB95, "RES 2,L");
            mnemonicos.put(0xCB96, "RES 2,(HL)");
            mnemonicos.put(0xCB97, "RES 2,A");
            mnemonicos.put(0xCB98, "RES 3,B");
            mnemonicos.put(0xCB99, "RES 3,C");
            mnemonicos.put(0xCB9A, "RES 3,D");
            mnemonicos.put(0xCB9B, "RES 3,E");
            mnemonicos.put(0xCB9C, "RES 3,H");
            mnemonicos.put(0xCB9D, "RES 3,L");
            mnemonicos.put(0xCB9E, "RES 3,(HL)");
            mnemonicos.put(0xCB9F, "RES 3,A");
            mnemonicos.put(0xCBA0, "RES 4,B");
            mnemonicos.put(0xCBA1, "RES 4,C");
            mnemonicos.put(0xCBA2, "RES 4,D");
            mnemonicos.put(0xCBA3, "RES 4,E");
            mnemonicos.put(0xCBA4, "RES 4,H");
            mnemonicos.put(0xCBA5, "RES 4,L");    
            mnemonicos.put(0xCBA6, "RES 4,(HL)");
            mnemonicos.put(0xCBA7, "RES 4,A");
            mnemonicos.put(0xCBA8, "RES 5,B");
            mnemonicos.put(0xCBA9, "RES 5,C");
            mnemonicos.put(0xCBAA, "RES 5,D");
            mnemonicos.put(0xCBAB, "RES 5,E");
            mnemonicos.put(0xCBAC, "RES 5,H");
            mnemonicos.put(0xCBAD, "RES 5,L");    
            mnemonicos.put(0xCBAE, "RES 5,(HL)");
            mnemonicos.put(0xCBAF, "RES 5,A");
            mnemonicos.put(0xCBB0, "RES 6,B");
            mnemonicos.put(0xCBB1, "RES 6,C");
            mnemonicos.put(0xCBB2, "RES 6,D");
            mnemonicos.put(0xCBB3, "RES 6,E");
            mnemonicos.put(0xCBB4, "RES 6,H");
            mnemonicos.put(0xCBB5, "RES 6,L");
            mnemonicos.put(0xCBB6, "RES 6,(HL)");
            mnemonicos.put(0xCBB7, "RES 6,A");
            mnemonicos.put(0xCBB8, "RES 7,B");
            mnemonicos.put(0xCBB9, "RES 7,C");
            mnemonicos.put(0xCBBA, "RES 7,D");
            mnemonicos.put(0xCBBB, "RES 7,E");
            mnemonicos.put(0xCBBC, "RES 7,H");
            mnemonicos.put(0xCBBD, "RES 7,L");
            mnemonicos.put(0xCBBE, "RES 7,(HL)");
            mnemonicos.put(0xCBBF, "RES 7,A");
            mnemonicos.put(0xCBC0, "SET 0,B");
            mnemonicos.put(0xCBC1, "SET 0,C");
            mnemonicos.put(0xCBC2, "SET 0,D");
            mnemonicos.put(0xCBC3, "SET 0,E");
            mnemonicos.put(0xCBC4, "SET 0,H");
            mnemonicos.put(0xCBC5, "SET 0,L");
            mnemonicos.put(0xCBC6, "SET 0,(HL)");
            mnemonicos.put(0xCBC7, "SET 0,A");
            mnemonicos.put(0xCBC8, "SET 1,B");
            mnemonicos.put(0xCBC9, "SET 1,C");
            mnemonicos.put(0xCBCA, "SET 1,D");
            mnemonicos.put(0xCBCB, "SET 1,E");
            mnemonicos.put(0xCBCC, "SET 1,H");
            mnemonicos.put(0xCBCD, "SET 1,L");
            mnemonicos.put(0xCBCE, "SET 1,(HL)");
            mnemonicos.put(0xCBCF, "SET 1,A");
            mnemonicos.put(0xCBD0, "SET 2,B");
            mnemonicos.put(0xCBD1, "SET 2,C");
            mnemonicos.put(0xCBD2, "SET 2,D");
            mnemonicos.put(0xCBD3, "SET 2,E");
            mnemonicos.put(0xCBD4, "SET 2,H");
            mnemonicos.put(0xCBD5, "SET 2,L");
            mnemonicos.put(0xCBD6, "SET 2,(HL)");
            mnemonicos.put(0xCBD7, "SET 2,A");
            mnemonicos.put(0xCBD8, "SET 3,B");
            mnemonicos.put(0xCBD9, "SET 3,C");
            mnemonicos.put(0xCBDA, "SET 3,D");
            mnemonicos.put(0xCBDB, "SET 3,E");
            mnemonicos.put(0xCBDC, "SET 3,H");
            mnemonicos.put(0xCBDD, "SET 3,L");
            mnemonicos.put(0xCBDE, "SET 3,(HL)");
            mnemonicos.put(0xCBDF, "SET 3,A");
            mnemonicos.put(0xCBE0, "SET 4,B");
            mnemonicos.put(0xCBE1, "SET 4,C");
            mnemonicos.put(0xCBE2, "SET 4,D");
            mnemonicos.put(0xCBE3, "SET 4,E");
            mnemonicos.put(0xCBE4, "SET 4,H");
            mnemonicos.put(0xCBE5, "SET 4,L");
            mnemonicos.put(0xCBE6, "SET 4,(HL)");
            mnemonicos.put(0xCBE7, "SET 4,A");
            mnemonicos.put(0xCBE8, "SET 5,B");
            mnemonicos.put(0xCBE9, "SET 5,C");
            mnemonicos.put(0xCBEA, "SET 5,D");
            mnemonicos.put(0xCBEB, "SET 5,E");
            mnemonicos.put(0xCBEC, "SET 5,H");
            mnemonicos.put(0xCBED, "SET 5,L");
            mnemonicos.put(0xCBEE, "SET 5,(HL)");
            mnemonicos.put(0xCBEF, "SET 5,A");
            mnemonicos.put(0xCBF0, "SET 6,B");
            mnemonicos.put(0xCBF1, "SET 6,C");
            mnemonicos.put(0xCBF2, "SET 6,D");
            mnemonicos.put(0xCBF3, "SET 6,E");
            mnemonicos.put(0xCBF4, "SET 6,H");
            mnemonicos.put(0xCBF5, "SET 6,L");
            mnemonicos.put(0xCBF6, "SET 6,(HL)");
            mnemonicos.put(0xCBF7, "SET 6,A");
            mnemonicos.put(0xCBF8, "SET 7,B");
            mnemonicos.put(0xCBF9, "SET 7,C");
            mnemonicos.put(0xCBFA, "SET 7,D");
            mnemonicos.put(0xCBFB, "SET 7,E");
            mnemonicos.put(0xCBFC, "SET 7,H");
            mnemonicos.put(0xCBFD, "SET 7,L");
            mnemonicos.put(0xCBFE, "SET 7,(HL)");
            mnemonicos.put(0xCBFF, "SET 7,A");
//MAIN INSTRUCTIONS
            mnemonicos.put(0xCC, "CALL Z, %04X");
        parametros.put(0xCC, 2);
            mnemonicos.put(0xCD, "CALL %04X");
        parametros.put(0xCD, 2);
            mnemonicos.put(0xCE, "ADC A, %02X");
        parametros.put(0xCE, 1);
            mnemonicos.put(0xCF, "RST 08h");
            mnemonicos.put(0xD0, "RET NC");
            mnemonicos.put(0xD1, "POP DE");
            mnemonicos.put(0xD2, "JP NC, %04X");
        parametros.put(0xD2, 2);
            mnemonicos.put(0xD3, "OUT (%02X), A");
        parametros.put(0xD3, 1);
            mnemonicos.put(0xD4, "CALL NC, %04X");
        parametros.put(0xD4, 2);
            mnemonicos.put(0xD5, "PUSH DE");
            mnemonicos.put(0xD6, "SUB %02X");
        parametros.put(0xD6, 1);
            mnemonicos.put(0xD7, "RST 10h");
            mnemonicos.put(0xD8, "RET C");
            mnemonicos.put(0xD9, "EXX");
            mnemonicos.put(0xDA, "JP C, %04X");
        parametros.put(0xDA, 2);
            mnemonicos.put(0xDB, "IN A, (%02X)");
        parametros.put(0xDB, 1);
            mnemonicos.put(0xDC, "CALL C, %04X");
        parametros.put(0xDC, 2);
        
            mnemonicos.put(0xDD09, "ADD IX, BC");
        
            mnemonicos.put(0xDD19, "ADD IX, DE");
            
            mnemonicos.put(0xDD21, "LD IX, %04X");
        parametros.put(0xDD21, 2);
            mnemonicos.put(0xDD22, "LD (%04X), IX");
        parametros.put(0xDD22, 2);
            mnemonicos.put(0xDD23, "INC IX");
            mnemonicos.put(0xDD24, "INC IXH");
            mnemonicos.put(0xDD25, "DEC IXH");
            mnemonicos.put(0xDD26, "LD IXH, %02X");
        parametros.put(0xDD26, 1);
            mnemonicos.put(0xDD29, "ADD IX, IX");
            mnemonicos.put(0xDD2A, "LD IX, (%04X)");
        parametros.put(0xDD2A, 2);
            mnemonicos.put(0xDD2B, "DEC IX");
            mnemonicos.put(0xDD2C, "INC IXL");
            mnemonicos.put(0xDD2D, "DEC IXL");
            mnemonicos.put(0xDD2E, "LD IXL, %02X");
        parametros.put(0xDD2E, 1);
            //0xDD2F
            //0xDD30
            //0xDD31
            //0xDD32
            //0xDD33
            mnemonicos.put(0xDD34, "INC (IX + %d)");
        parametros.put(0xDD34, 1);
            mnemonicos.put(0xDD35, "DEC (IX + %d)");
            parametros.put(0xDD35, 1);
            mnemonicos.put(0xDD36, "LD (IX + %d), %02X");
        parametros.put(0xDD36, 2);

            mnemonicos.put(0xDD39, "ADD IX, SP");
            
            mnemonicos.put(0xDD44, "LD B, IXH");
            mnemonicos.put(0xDD45, "LD B, IXL");
            mnemonicos.put(0xDD46, "LD B, (IX + %d)");
            parametros.put(0xDD46, 1);

            mnemonicos.put(0xDD4C, "LD C, IXH");
            mnemonicos.put(0xDD4D, "LD C, IXL");
            mnemonicos.put(0xDD4E, "LD C, (IX + %d)");
            parametros.put(0xDD4E, 1);

            mnemonicos.put(0xDD54, "LD D, IXH");
            mnemonicos.put(0xDD55, "LD D, IXL");
            mnemonicos.put(0xDD56, "LD D, (IX + %d)");
            parametros.put(0xDD56, 1);

            mnemonicos.put(0xDD5C, "LD E, IXH");
            mnemonicos.put(0xDD5D, "LD E, IXL");
            mnemonicos.put(0xDD5E, "LD E, (IX + %d)");
            parametros.put(0xDD5E, 1);

            mnemonicos.put(0xDD60, "LD IXH, B");
            mnemonicos.put(0xDD61, "LD IXH, C");
            mnemonicos.put(0xDD62, "LD IXH, D");
            mnemonicos.put(0xDD63, "LD IXH, E");
            mnemonicos.put(0xDD64, "LD IXH, IXH");
            mnemonicos.put(0xDD65, "LD IXH, IXL");
            mnemonicos.put(0xDD66, "LD H, (IX + %d)");
            parametros.put(0xDD66,1);
            mnemonicos.put(0xDD67, "LD IXH, A");
            mnemonicos.put(0xDD68, "LD IXL, B");
            mnemonicos.put(0xDD69, "LD IXL, C");
            mnemonicos.put(0xDD6A, "LD IXL, D");
            mnemonicos.put(0xDD6B, "LD IXL, E");
            mnemonicos.put(0xDD6C, "LD IXL, IXH");
            mnemonicos.put(0xDD6D, "LD IXL, IXL");
            mnemonicos.put(0xDD6E, "LD L, (IX + %d)");
            parametros.put(0xDD6E, 1);

            mnemonicos.put(0xDD6F, "LD IXL, A");
            mnemonicos.put(0xDD70, "LD (IX + %d), B");
            parametros.put(0xDD70, 1);
            mnemonicos.put(0xDD71, "LD (IX + %d), C");
            parametros.put(0xDD71, 1);
            mnemonicos.put(0xDD72, "LD (IX + %d), D");
            parametros.put(0xDD72, 1);
            mnemonicos.put(0xDD73, "LD (IX + %d), E");
            parametros.put(0xDD73, 1);
            mnemonicos.put(0xDD74, "LD (IX + %d), H");
            parametros.put(0xDD74,1);
            mnemonicos.put(0xDD75, "LD (IX + %d), L");
            parametros.put(0xDD75, 1);
            mnemonicos.put(0xDD77, "LD (IX + %d), A");
            parametros.put(0xDD77, 1);

            mnemonicos.put(0xDD7C, "LD A, IXH");
            mnemonicos.put(0xDD7D, "LD A, IXL");
            mnemonicos.put(0xDD7E, "LD A, (IX + %d)");
            parametros.put(0xDD7E,1);

            mnemonicos.put(0xDD84, "ADD A, IXH");
            mnemonicos.put(0xDD85, "ADD A, IXL");
            mnemonicos.put(0xDD86, "ADD A,(IX + %d)");
            parametros.put(0xDD86, 1);

            mnemonicos.put(0xDD8C, "ADC IXH");
            mnemonicos.put(0xDD8D, "ADC IXL");
            mnemonicos.put(0xDD8E, "ADC A,(IX + %d)");
            parametros.put(0xDD8E, 1);

            mnemonicos.put(0xDD8F, "ADC A");
  
            mnemonicos.put(0xDD94, "SUB IXH");
            mnemonicos.put(0xDD95, "SUB IXL");
            mnemonicos.put(0xDD96, "SUB (IX + %d)");
            parametros.put(0xDD96, 1);
            mnemonicos.put(0xDD98, "SBC B");
            mnemonicos.put(0xDD99, "SBC C");
            mnemonicos.put(0xDD9A, "SBC D");
            mnemonicos.put(0xDD9B, "SBC E");
            mnemonicos.put(0xDD9C, "SBC IXH");
            mnemonicos.put(0xDD9D, "SBC IXL");
            mnemonicos.put(0xDD9E, "SBC A, (IX + %d)");
            parametros.put(0xDD9E, 1);
            mnemonicos.put(0xDD9F, "SBC A");
            mnemonicos.put(0xDDA0, "AND B");
            mnemonicos.put(0xDDA1, "AND C");
            mnemonicos.put(0xDDA2, "AND D");
            mnemonicos.put(0xDDA3, "AND E");
            mnemonicos.put(0xDDA4, "AND IXH");
            mnemonicos.put(0xDDA5, "AND IXL");
            mnemonicos.put(0xDDA6, "AND (IX + %d)");
            parametros.put(0xDDA6, 1);
            mnemonicos.put(0xDDA7, "AND A");
            mnemonicos.put(0xDDA8, "XOR B");
            mnemonicos.put(0xDDA9, "XOR C");
            mnemonicos.put(0xDDAA, "XOR D");
            mnemonicos.put(0xDDAB, "XOR E");
            mnemonicos.put(0xDDAC, "XOR IXH");
            mnemonicos.put(0xDDAD, "XOR IXL");
            mnemonicos.put(0xDDAE, "XOR (IX + %d)");
            parametros.put(0xDDAE, 1);
            mnemonicos.put(0xDDAF, "XOR A");
            mnemonicos.put(0xDDB0, "OR B");
            mnemonicos.put(0xDDB1, "OR C");
            mnemonicos.put(0xDDB2, "OR D");
            mnemonicos.put(0xDDB3, "OR E");
            mnemonicos.put(0xDDB4, "OR IXH");
            mnemonicos.put(0xDDB5, "OR IXL");
            mnemonicos.put(0xDDB6, "OR (IX + %d)");
            parametros.put(0xDDB6, 1);
            mnemonicos.put(0xDDB7, "OR A");
            mnemonicos.put(0xDDB8, "CP B");
            mnemonicos.put(0xDDB9, "CP C");
            mnemonicos.put(0xDDBA, "CP D");
            mnemonicos.put(0xDDBB, "CP E");
            mnemonicos.put(0xDDBC, "CP IXH");
            mnemonicos.put(0xDDBD, "CP IXL");
            mnemonicos.put(0xDDBE, "CP (IX + %d)");
            parametros.put(0xDDBE, 1);
            mnemonicos.put(0xDDBF, "CP A");
            
            //IX BIT
            mnemonicos.put(0xDDCB06, "RLC (IX + %d)");
            parametros.put(0xDDCB06, 1);
            mnemonicos.put(0xDDCB0E, "RRC (IX + %d)");
            parametros.put(0xDDCB0E, 1);
            mnemonicos.put(0xDDCB16, "RL (IX + %d)");
            parametros.put(0xDDCB16, 1);
            mnemonicos.put(0xDDCB1E, "RR (IX + %d)");
            parametros.put(0xDDCB1E, 1);
            mnemonicos.put(0xDDCB26, "SLA (IX + %d)");
            parametros.put(0xDDCB26, 1);
            mnemonicos.put(0xDDCB2E, "SRA (IX + %d)");
            parametros.put(0xDDCB2E, 1);
            mnemonicos.put(0xDDCB36, "SLL (IX + %d)");
            parametros.put(0xDDCB36, 1);
            mnemonicos.put(0xDDCB3E, "SRL (IX + %d)");
            parametros.put(0xDDCB3E, 1);
            mnemonicos.put(0xDDCB46, "BIT 0, (IX + %d)");
            parametros.put(0xDDCB46, 1);
            mnemonicos.put(0xDDCB4E, "BIT 1, (IX + %d)");
            parametros.put(0xDDCB4E, 1);
            mnemonicos.put(0xDDCB56, "BIT 2, (IX + %d)");
            parametros.put(0xDDCB56, 1);
            mnemonicos.put(0xDDCB5E, "BIT 3, (IX + %d)");
            parametros.put(0xDDCB5E, 1);
            mnemonicos.put(0xDDCB66, "BIT 4, (IX + %d)");
            parametros.put(0xDDCB66, 1);
            mnemonicos.put(0xDDCB6E, "BIT 5, (IX + %d)");
            parametros.put(0xDDCB6E, 1);
            mnemonicos.put(0xDDCB76, "BIT 6, (IX + %d)");
            parametros.put(0xDDCB76, 1);
            mnemonicos.put(0xDDCB7E, "BIT 7, (IX + %d)");
            parametros.put(0xDDCB7E, 1);
            mnemonicos.put(0xDDCB86, "RES 0, (IX + %d)");
            parametros.put(0xDDCB86, 1);
            mnemonicos.put(0xDDCB8E, "RES 1, (IX + %d)");
            parametros.put(0xDDCB8E, 1);
            mnemonicos.put(0xDDCB96, "RES 2, (IX + %d)");
            parametros.put(0xDDCB96, 1);
            mnemonicos.put(0xDDCB9E, "RES 3, (IX + %d)");
            parametros.put(0xDDCB9E, 1);
            mnemonicos.put(0xDDCBA6, "RES 4, (IX + %d)");
            parametros.put(0xDDCBA6, 1);
            mnemonicos.put(0xDDCBAE, "RES 5, (IX + %d)");
            parametros.put(0xDDCBAE, 1);
            mnemonicos.put(0xDDCBB6, "RES 6, (IX + %d)");
            parametros.put(0xDDCBB6, 1);
            mnemonicos.put(0xDDCBBE, "RES 7, (IX + %d)");
            parametros.put(0xDDCBBE, 1);
            mnemonicos.put(0xDDCBC6, "SET 0, (IX + %d)");
            parametros.put(0xDDCBC6, 1);
            mnemonicos.put(0xDDCBCE, "SET 1, (IX + %d)");
            parametros.put(0xDDCBCE, 1);
            mnemonicos.put(0xDDCBD6, "SET 2, (IX + %d)");
            parametros.put(0xDDCBD6, 1);
            mnemonicos.put(0xDDCBDE, "SET 3, (IX + %d)");
            parametros.put(0xDDCBDE, 1);
            mnemonicos.put(0xDDCBE6, "SET 4, (IX + %d)");
            parametros.put(0xDDCBE6, 1);
            mnemonicos.put(0xDDCBEE, "SET 5, (IX + %d)");
            parametros.put(0xDDCBEE, 1);
            mnemonicos.put(0xDDCBF6, "SET 6, (IX + %d)");
            parametros.put(0xDDCBF6, 1);
            mnemonicos.put(0xDDCBFE, "SET 7, (IX + %d)");            
            parametros.put(0xDDCBFE, 1);

            mnemonicos.put(0xDDE1, "POP IX");
            mnemonicos.put(0xDDE3, "EX (SP), IX");
            mnemonicos.put(0xDDE5, "PUSH IX");

            mnemonicos.put(0xDDE9, "JP (IX)");
            
            mnemonicos.put(0xDDF9, "LD SP, IX");
  
            mnemonicos.put(0xDE, "SBC A, %02X");
        parametros.put(0xDE, 1);
            mnemonicos.put(0xDF, "RST 18h");
            mnemonicos.put(0xE0, "RET PO");
            mnemonicos.put(0xE1, "POP HL");
            mnemonicos.put(0xE2, "JP PO, %04X");
        parametros.put(0xE2, 2);
            mnemonicos.put(0xE3, "EX (SP), HL");
            mnemonicos.put(0xE4, "CALL PO, %04X");
        parametros.put(0xE4, 2);
            mnemonicos.put(0xE5, "PUSH HL");
            mnemonicos.put(0xE6, "AND %02X");
        parametros.put(0xE6, 1);
            mnemonicos.put(0xE7, "RST 20h");
            mnemonicos.put(0xE8, "RET PE");
            mnemonicos.put(0xE9, "JP (HL)");
            mnemonicos.put(0xEA, "JP PE, %04X");
        parametros.put(0xEA, 2);
            mnemonicos.put(0xEB, "EX DE, HL");
            mnemonicos.put(0xEC, "CALL PE, %04X");
        parametros.put(0xEC, 2);
        
        //INSTRUCCIONES MISC.
            mnemonicos.put(0xED00, "IN0 B, (%02X)");
        parametros.put(0xED00, 1);
            mnemonicos.put(0xED01, "OUT0 (%02X), B");
        parametros.put(0xED01, 1);
            mnemonicos.put(0xED04, "TST B");
            mnemonicos.put(0xED08, "IN0 C,(%02X)");
        parametros.put(0xED08, 1);
            mnemonicos.put(0xED09, "OUT0 (%02X), C");
        parametros.put(0xED09, 1);
            mnemonicos.put(0xED0C, "TST C");
            mnemonicos.put(0xED10, "IN0 D, (%02X)");
        parametros.put(0xED10, 1);
            mnemonicos.put(0xED11, "OUT0 (%02X),D");
        parametros.put(0xED11, 2);
            mnemonicos.put(0xED14, "TST D");
            mnemonicos.put(0xED18, "IN0 E,(%02X)");
        parametros.put(0xED18, 1);
            mnemonicos.put(0xED19, "OUT0 (%02X), E");
        parametros.put(0xED19, 1);
            mnemonicos.put(0xED1C, "TST E");
            mnemonicos.put(0xED20, "IN0 H,(%02X)");
        parametros.put(0xED20, 1);
            mnemonicos.put(0xED21, "OUT0 (%02X),H");
        parametros.put(0xED21, 1);
            mnemonicos.put(0xED24, "TST H");
            mnemonicos.put(0xED28, "IN0 L,(%02X)");
        parametros.put(0xED28, 1);
            mnemonicos.put(0xED29, "OUT0 (%02X), L");
        parametros.put(0xED29, 1);
            mnemonicos.put(0xED2C, "TST L");
            mnemonicos.put(0xED34, "TST (HL)");
            mnemonicos.put(0xED38, "IN0 A,(%02X)");
        parametros.put(0xED38, 1);
            mnemonicos.put(0xED39, "OUT0 (%02X), A");
        parametros.put(0xED39, 1);
            mnemonicos.put(0xED3C, "TST A");
            mnemonicos.put(0xED40, "IN B,(C)");
            mnemonicos.put(0xED41, "OUT (C), B");
            mnemonicos.put(0xED42, "SBC HL,BC");
            mnemonicos.put(0xED43, "LD (%04X), BC");
        parametros.put(0xED43, 2);
            mnemonicos.put(0xED44, "NEG");
            mnemonicos.put(0xED45, "RETN");
            mnemonicos.put(0xED46, "IM 0" );
            mnemonicos.put(0xED47, "LD I, A");
            mnemonicos.put(0xED48, "IN C, (C)");
            mnemonicos.put(0xED49, "OUT (C), C");
            mnemonicos.put(0xED4A, "ADC HL, BC");
            mnemonicos.put(0xED4B, "LD BC, (%04X)");
        parametros.put(0xED4B, 2);
            mnemonicos.put(0xED4C, "MLT BC");
            mnemonicos.put(0xED4D, "RETI");
            mnemonicos.put(0xED4F, "LD R, A");
            mnemonicos.put(0xED50, "IN D, (C)");
            mnemonicos.put(0xED51, "OUT (C), D");
            mnemonicos.put(0xED52, "SBC HL, DE");
            mnemonicos.put(0xED53, "LD (%04X), DE");
        parametros.put(0xED53, 2);
            mnemonicos.put(0xED56, "IM 1" );
            mnemonicos.put(0xED57, "LD A, I");
            mnemonicos.put(0xED58, "IN E,(C)");
            mnemonicos.put(0xED59, "OUT (C), E");
            mnemonicos.put(0xED5B, "LD DE, (%04X)");
        parametros.put(0xED5B, 2);
            mnemonicos.put(0xED5C, "MLT DE");
            mnemonicos.put(0xED5E, "IM 2");
            mnemonicos.put(0xED5F, "LD A, R");
            mnemonicos.put(0xED60, "IN H,(C)");
            mnemonicos.put(0xED61, "OUT (C), H");
            mnemonicos.put(0xED62, "SBC HL, HL");
            mnemonicos.put(0xED64, "TST %02X");
        parametros.put(0xED64, 1);
            mnemonicos.put(0xED67, "RRD");
            mnemonicos.put(0xED68, "IN L,(C)");
            mnemonicos.put(0xED69, "OUT (C), L");
            mnemonicos.put(0xED6A, "ADC HL, HL");

            mnemonicos.put(0xED6C, "MLT HL");
            mnemonicos.put(0xED6F, "RLD");
            mnemonicos.put(0xED70, "IN (C)" );
            mnemonicos.put(0xED71, "OUT (C), 0");
            mnemonicos.put(0xED72, "SBC HL, SP");
            mnemonicos.put(0xED73, "LD (%04X), SP");
        parametros.put(0xED73, 2);
            mnemonicos.put(0xED74, "TSTIO %02X");
        parametros.put(0xED74, 1);
            mnemonicos.put(0xED76, "SLP");
            mnemonicos.put(0xED78, "IN A,(C)");
            mnemonicos.put(0xED79, "OUT (C), A");
            mnemonicos.put(0xED7A, "ADC HL, SP");
            mnemonicos.put(0xED7B, "LD SP, (%04X)");
        parametros.put(0xED7B, 2);
            mnemonicos.put(0xED7C, "MLT SP");
            mnemonicos.put(0xED83, "OTIM");
            mnemonicos.put(0xED8B, "OTDM");
            mnemonicos.put(0xED93, "OTIMR");
            mnemonicos.put(0xED9B, "OTDMR");
            mnemonicos.put(0xEDA0, "LDI");
            mnemonicos.put(0xEDA1, "CPI");
            mnemonicos.put(0xEDA2, "INI");
            mnemonicos.put(0xEDA3, "OUTI");
            mnemonicos.put(0xEDA8, "LDD");
            mnemonicos.put(0xEDA9, "CPD");
            mnemonicos.put(0xEDAA, "IND");
            mnemonicos.put(0xEDAB, "OUTD");
            mnemonicos.put(0xEDB0, "LDIR");
            mnemonicos.put(0xEDB1, "CPIR");
            mnemonicos.put(0xEDB2, "INIR");
            mnemonicos.put(0xEDB3, "OTIR");
            mnemonicos.put(0xEDB8, "LDDR");
            mnemonicos.put(0xEDB9, "CPDR");
            mnemonicos.put(0xEDBA, "INDR");
            mnemonicos.put(0xEDBB, "OTDR");
//MAIN INSTRUCTIONS
            mnemonicos.put(0xEE, "XOR %02X");
        parametros.put(0xEE, 1);
            mnemonicos.put(0xEF, "RST 28h");
            mnemonicos.put(0xF0, "RET P");
            mnemonicos.put(0xF1, "POP AF");
            mnemonicos.put(0xF2, "JP P, %04X");
        parametros.put(0xF2, 2);
            mnemonicos.put(0xF3, "DI");
            mnemonicos.put(0xF4, "CALL P, %04X");
        parametros.put(0xF4, 2);
            mnemonicos.put(0xF5, "PUSH AF");
            mnemonicos.put(0xF6, "OR %02X");
        parametros.put(0xF6, 1);
            mnemonicos.put(0xF7, "RST 30h");
            mnemonicos.put(0xF8, "RET M");
            mnemonicos.put(0xF9, "LD SP, HL");
            mnemonicos.put(0xFA, "JP M, %04X");
        parametros.put(0xFA, 2);
            mnemonicos.put(0xFB, "EI");
            mnemonicos.put(0xFC, "CALL M, %04X");
        parametros.put(0xFC, 2);

        //IY
            mnemonicos.put(0xFD09, "ADD IY, BC");
            mnemonicos.put(0xFD19, "ADD IY, DE");
            mnemonicos.put(0xFD21, "LD IY, %04X");
        parametros.put(0xFD21, 2);
            mnemonicos.put(0xFD22, "LD (%04X), IY");
        parametros.put(0xFD22, 2);
            mnemonicos.put(0xFD23, "INC IY");
            mnemonicos.put(0xFD29, "ADD IY, IY");
            mnemonicos.put(0xFD2A, "LD IY, (%04X)");
        parametros.put(0xFD2A, 2);
            mnemonicos.put(0xFD2B, "DEC IY");
            mnemonicos.put(0xFD34, "INC (IY + %d)");
            parametros.put(0xFD34, 1);
            mnemonicos.put(0xFD35, "DEC (IY + %d)");
            parametros.put(0xFD35, 1);
            mnemonicos.put(0xFD36, "LD (IY + %d), %02X");
        parametros.put(0xFD36, 2);
            mnemonicos.put(0xFD39, "ADD IY, SP");
            mnemonicos.put(0xFD46, "LD B, (IY + %d)");
            parametros.put(0xFD46, 1);
            mnemonicos.put(0xFD4E, "LD C, (IY + %d)");
            parametros.put(0xFD4E, 1);
            mnemonicos.put(0xFD56, "LD D, (IY + %d)");
            parametros.put(0xFD56, 1);
            mnemonicos.put(0xFD5E, "LD E, (IY + %d)");
            parametros.put(0xFD5E, 1);
            mnemonicos.put(0xFD66, "LD H, (IY + %d)");
            parametros.put(0xFD66, 1);
            mnemonicos.put(0xFD6E, "LD L, (IY + %d)");
            parametros.put(0xFD6E, 1);
            mnemonicos.put(0xFD70, "LD (IY + %d), B");
            parametros.put(0xFD70, 1);
            mnemonicos.put(0xFD71, "LD (IY + %d), C");
            parametros.put(0xFD71, 1);
            mnemonicos.put(0xFD72, "LD (IY + %d), D");
            parametros.put(0xFD72, 1);
            mnemonicos.put(0xFD73, "LD (IY + %d), E");
            parametros.put(0xFD73, 1);
            mnemonicos.put(0xFD74, "LD (IY + %d), H");
            parametros.put(0xFD74, 1);
            mnemonicos.put(0xFD75, "LD (IY + %d), L");
            parametros.put(0xFD75, 1);
            mnemonicos.put(0xFD77, "LD (IY + %d), A");
            parametros.put(0xFD77, 1);
            mnemonicos.put(0xFD7E, "LD A, (IY + %d)");
            parametros.put(0xFD7E, 1);

            mnemonicos.put(0xFD86, "ADD A, (IY + %d)");
            parametros.put(0xFD86, 1);
            mnemonicos.put(0xFD8E, "ADC A, (IY + %d)");
            parametros.put(0xFD8E, 1);
            mnemonicos.put(0xFD96, "SUB (IY + %d)");
            parametros.put(0xFD96, 1);
            mnemonicos.put(0xFD9E, "SBC A, (IY + %d)");
            parametros.put(0xFD9E, 1);
            mnemonicos.put(0xFDA6, "AND (IY + %d)");
            parametros.put(0xFDA6, 1);
            mnemonicos.put(0xFDAE, "XOR (IY + %d)");
            parametros.put(0xFDAE, 1);
            mnemonicos.put(0xFDB6, "OR (IY + %d)");
            parametros.put(0xFDB6, 1);
            mnemonicos.put(0xFDBE, "CP (IY + %d)");
            parametros.put(0xFDBE, 1);
            //IY BIT
            mnemonicos.put(0xFDCB06, "RLC (IY + %d)");
            parametros.put(0xFDCB06, 1);
            mnemonicos.put(0xFDCB0E, "RRC (IY + %d)");
            parametros.put(0xFDCB0E, 1);
            mnemonicos.put(0xFDCB16, "RL (IY + %d)");
            parametros.put(0xFDCB16, 1);
            mnemonicos.put(0xFDCB1E, "RR (IY + %d)");
            parametros.put(0xFDCB1E, 1);
            mnemonicos.put(0xFDCB26, "SLA (IY + %d)");
            parametros.put(0xFDCB26, 1);
            mnemonicos.put(0xFDCB2E, "SRA (IY + %d)");
            parametros.put(0xFDCB2E, 1);
            mnemonicos.put(0xFDCB3E, "SRL (IY + %d)");
            parametros.put(0xFDCB3E, 1);
            mnemonicos.put(0xFDCB46, "BIT 0, (IY + %d)");
            parametros.put(0xFDCB46, 1);
            mnemonicos.put(0xFDCB4E, "BIT 1, (IY + %d)");
            parametros.put(0xFDCB4E, 1);
            mnemonicos.put(0xFDCB56, "BIT 2, (IY + %d)");
            parametros.put(0xFDCB56, 1);
            mnemonicos.put(0xFDCB5E, "BIT 3, (IY + %d)");
            parametros.put(0xFDCB5E, 1);
            mnemonicos.put(0xFDCB66, "BIT 4, (IY + %d)");
            parametros.put(0xFDCB66, 1);
            mnemonicos.put(0xFDCB6E, "BIT 5, (IY + %d)");
            parametros.put(0xFDCB6E, 1);
            mnemonicos.put(0xFDCB76, "BIT 6, (IY + %d)");
            parametros.put(0xFDCB76, 1);
            mnemonicos.put(0xFDCB7E, "BIT 7, (IY + %d)");
            parametros.put(0xFDCB7E, 1);
            mnemonicos.put(0xFDCB86, "RES 0, (IY + %d)");
            parametros.put(0xFDCB86, 1);
            mnemonicos.put(0xFDCB8E, "RES 1, (IY + %d)");
            parametros.put(0xFDCB8E, 1);
            mnemonicos.put(0xFDCB96, "RES 2, (IY + %d)");
            parametros.put(0xFDCB96, 1);
            mnemonicos.put(0xFDCB9E, "RES 3, (IY + %d)");
            parametros.put(0xFDCB9E, 1);
            mnemonicos.put(0xFDCBA6, "RES 4, (IY + %d)");
            parametros.put(0xFDCBA6, 1);
            mnemonicos.put(0xFDCBAE, "RES 5, (IY + %d)");
            parametros.put(0xFDCBAE, 1);
            mnemonicos.put(0xFDCBB6, "RES 6, (IY + %d)");
            parametros.put(0xFDCBB6, 1);
            mnemonicos.put(0xFDCBBE, "RES 7, (IY + %d)");
            parametros.put(0xFDCBBE, 1);
            mnemonicos.put(0xFDCBC6, "SET 0, (IY + %d)");
            parametros.put(0xFDCBC6, 1);
            mnemonicos.put(0xFDCBCE, "SET 1, (IY + %d)");
            parametros.put(0xFDCBCE, 1);
            mnemonicos.put(0xFDCBD6, "SET 2, (IY + %d)");
            parametros.put(0xFDCBD6, 1);
            mnemonicos.put(0xFDCBDE, "SET 3, (IY + %d)");
            parametros.put(0xFDCBDE, 1);
            mnemonicos.put(0xFDCBE6, "SET 4, (IY + %d)");
            parametros.put(0xFDCBE6, 1);
            mnemonicos.put(0xFDCBEE, "SET 5, (IY + %d)");
            parametros.put(0xFDCBEE, 1);
            mnemonicos.put(0xFDCBF6, "SET 6, (IY + %d)");
            parametros.put(0xFDCBF6, 1);
            mnemonicos.put(0xFDCBFE, "SET 7, (IY + %d)");
            parametros.put(0xFDCBFE, 1);
        //IY
            mnemonicos.put(0xFDE1, "POP IY");
            mnemonicos.put(0xFDE3, "EX (SP), IY");
            mnemonicos.put(0xFDE5, "PUSH IY");
            mnemonicos.put(0xFDE9, "JP (IY)");
            mnemonicos.put(0xFDF9, "LD SP, IY");
//MAIN INSTRUCTIONS
            mnemonicos.put(0xFE, "CP %02X");
            parametros.put(0xFE, 1);
            mnemonicos.put(0xFF, "RST 38h");      
    }

    public static String getMnemonico(int opcode) {
        if (mnemonicos.containsKey(opcode)) {
            return mnemonicos.get(opcode);
        } else {
            return "**Instruccion desconocida**";
        }
    }

    public static int getParametro(int opcode) {
        if (parametros.containsKey(opcode)) {
            return parametros.get(opcode);
        } else {
            return 0;
        }
    }
}
